const mongoose = require('mongoose')

// Read MongoDB URI from .env.local file
const fs = require('fs')
const path = require('path')
const envPath = path.join(__dirname, '..', '.env.local')
const envContent = fs.readFileSync(envPath, 'utf8')
const MONGODB_URI = envContent.split('\n').find(line => line.startsWith('MONGODB_URI=')).split('=')[1].trim()

const TemplateSchema = new mongoose.Schema({
  name: String,
  category: String,
  icon: String,
  desc: String,
  color: String,
  accentColor: String,
  tags: [String],
  popular: Boolean,
  isActive: Boolean,
  showOnHomepage: Boolean,
  previewImage: String,
  files: [String],
  usageCount: Number,
  templateType: String,
  config: {
    headingFont: String,
    bodyFont: String,
    baseFontSize: Number,
    navbarStyle: String,
    showNavCTA: Boolean,
    navCTAText: String,
    primaryColor: String,
    secondaryColor: String,
    bgLight: String,
    bgDark: String,
    cardBg: String,
    textColor: String,
    sections: {
      hero: Boolean,
      features: Boolean,
      services: Boolean,
      testimonials: Boolean,
      gallery: Boolean,
      faq: Boolean,
      contactForm: Boolean,
      footer: Boolean,
    },
    footerColumns: Number,
    footerCopyright: String,
    socialLinks: {
      facebook: String,
      instagram: String,
      twitter: String,
      youtube: String,
      linkedin: String,
    },
    logoUrl: String,
    faviconUrl: String,
    heroLayout: String,
    heroTitle: String,
    heroSubtitle: String,
    heroBgImage: String,
    heroCTAText: String,
  },
}, { timestamps: true })

const Template = mongoose.models.Template || mongoose.model('Template', TemplateSchema)

const templates = [
  {
    name: 'Modern Restaurant',
    category: 'Food & Dining',
    icon: '🍴',
    desc: 'Fine dining template with menu, reservations, and WhatsApp ordering',
    color: 'linear-gradient(135deg, #c2410c, #ea580c)',
    accentColor: '#c2410c',
    tags: ['Menu', 'WhatsApp', 'Booking', 'Restaurant'],
    popular: true,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'sticky',
      showNavCTA: true,
      navCTAText: 'Book Table',
      primaryColor: '#c2410c',
      secondaryColor: '#ea580c',
      bgLight: '#FFFFFF',
      bgDark: '#1c0a00',
      cardBg: '#fff7ed',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: true, faq: true, contactForm: true, footer: true },
      footerColumns: 3,
      footerCopyright: '© 2026 Modern Restaurant. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'centered',
      heroTitle: 'Experience Fine Dining',
      heroSubtitle: 'Authentic flavors, elegant ambiance, unforgettable moments',
      heroBgImage: '',
      heroCTAText: 'View Menu',
    },
  },
  {
    name: 'Luxury Hotel',
    category: 'Hotels & Stays',
    icon: '🏨',
    desc: 'Premium hotel showcase with rooms, amenities, and booking system',
    color: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
    accentColor: '#1e3a8a',
    tags: ['Rooms', 'Booking', 'Luxury', 'Hotel'],
    popular: true,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'sticky',
      showNavCTA: true,
      navCTAText: 'Book Now',
      primaryColor: '#1e3a8a',
      secondaryColor: '#3b82f6',
      bgLight: '#FFFFFF',
      bgDark: '#0f172a',
      cardBg: '#eff6ff',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: true, faq: true, contactForm: true, footer: true },
      footerColumns: 4,
      footerCopyright: '© 2026 Luxury Hotel. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'fullscreen',
      heroTitle: 'Your Home Away From Home',
      heroSubtitle: '5-star luxury accommodation with world-class service',
      heroBgImage: '',
      heroCTAText: 'Explore Rooms',
    },
  },
  {
    name: 'Digital Agency',
    category: 'Business',
    icon: '💡',
    desc: 'Creative agency template with portfolio, services, and contact form',
    color: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
    accentColor: '#4f46e5',
    tags: ['Agency', 'Portfolio', 'Services', 'Creative'],
    popular: true,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Syne',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'minimal',
      showNavCTA: true,
      navCTAText: 'Get Started',
      primaryColor: '#4f46e5',
      secondaryColor: '#7c3aed',
      bgLight: '#FFFFFF',
      bgDark: '#0f172a',
      cardBg: '#f5f3ff',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: true, faq: true, contactForm: true, footer: true },
      footerColumns: 3,
      footerCopyright: '© 2026 Digital Agency. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'split',
      heroTitle: 'We Build Digital Experiences',
      heroSubtitle: 'Transform your brand with cutting-edge design and development',
      heroBgImage: '',
      heroCTAText: 'View Portfolio',
    },
  },
  {
    name: 'Gym & Fitness',
    category: 'Health & Fitness',
    icon: '💪',
    desc: 'High-energy gym template with classes, trainers, and membership plans',
    color: 'linear-gradient(135deg, #dc2626, #f97316)',
    accentColor: '#dc2626',
    tags: ['Gym', 'Fitness', 'Classes', 'Training'],
    popular: true,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Outfit',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'sticky',
      showNavCTA: true,
      navCTAText: 'Join Now',
      primaryColor: '#dc2626',
      secondaryColor: '#f97316',
      bgLight: '#FFFFFF',
      bgDark: '#1c0000',
      cardBg: '#fff1f2',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: false, faq: true, contactForm: true, footer: true },
      footerColumns: 3,
      footerCopyright: '© 2026 Gym & Fitness. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'centered',
      heroTitle: 'Transform Your Body',
      heroSubtitle: 'Join the best fitness community and achieve your goals',
      heroBgImage: '',
      heroCTAText: 'Start Free Trial',
    },
  },
  {
    name: 'Cafe & Bakery',
    category: 'Food & Dining',
    icon: '☕',
    desc: 'Cozy cafe template with menu, daily specials, and online ordering',
    color: 'linear-gradient(135deg, #92400e, #d97706)',
    accentColor: '#92400e',
    tags: ['Cafe', 'Bakery', 'Menu', 'Coffee'],
    popular: false,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Lora',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'sticky',
      showNavCTA: true,
      navCTAText: 'Order Online',
      primaryColor: '#92400e',
      secondaryColor: '#d97706',
      bgLight: '#FFFFFF',
      bgDark: '#1c0a00',
      cardBg: '#fef3c7',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: true, faq: true, contactForm: true, footer: true },
      footerColumns: 3,
      footerCopyright: '© 2026 Cafe & Bakery. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'centered',
      heroTitle: 'Fresh Brewed Daily',
      heroSubtitle: 'Artisan coffee, homemade pastries, warm atmosphere',
      heroBgImage: '',
      heroCTAText: 'See Menu',
    },
  },
  {
    name: 'Medical Clinic',
    category: 'Healthcare',
    icon: '🏥',
    desc: 'Professional clinic template with doctors, services, and appointments',
    color: 'linear-gradient(135deg, #0369a1, #0284c7)',
    accentColor: '#0369a1',
    tags: ['Medical', 'Clinic', 'Doctors', 'Healthcare'],
    popular: true,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Roboto',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'sticky',
      showNavCTA: true,
      navCTAText: 'Book Appointment',
      primaryColor: '#0369a1',
      secondaryColor: '#0284c7',
      bgLight: '#FFFFFF',
      bgDark: '#0f172a',
      cardBg: '#f0f9ff',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: false, faq: true, contactForm: true, footer: true },
      footerColumns: 4,
      footerCopyright: '© 2026 Medical Clinic. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'split',
      heroTitle: 'Your Health, Our Priority',
      heroSubtitle: 'Expert medical care with compassion and excellence',
      heroBgImage: '',
      heroCTAText: 'Find a Doctor',
    },
  },
  {
    name: 'Salon & Spa',
    category: 'Beauty & Wellness',
    icon: '💅',
    desc: 'Elegant salon template with services, gallery, and booking system',
    color: 'linear-gradient(135deg, #9d174d, #ec4899)',
    accentColor: '#9d174d',
    tags: ['Salon', 'Spa', 'Beauty', 'Wellness'],
    popular: true,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'minimal',
      showNavCTA: true,
      navCTAText: 'Book Now',
      primaryColor: '#9d174d',
      secondaryColor: '#ec4899',
      bgLight: '#FFFFFF',
      bgDark: '#1c0a00',
      cardBg: '#fdf2f8',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: true, faq: true, contactForm: true, footer: true },
      footerColumns: 3,
      footerCopyright: '© 2026 Salon & Spa. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'centered',
      heroTitle: 'Beauty & Relaxation',
      heroSubtitle: 'Premium salon services in a luxurious environment',
      heroBgImage: '',
      heroCTAText: 'View Services',
    },
  },
  {
    name: 'Real Estate',
    category: 'Property',
    icon: '🏠',
    desc: 'Property listing template with search, filters, and contact forms',
    color: 'linear-gradient(135deg, #065f46, #059669)',
    accentColor: '#059669',
    tags: ['Real Estate', 'Property', 'Listing', 'Homes'],
    popular: false,
    isActive: true,
    showOnHomepage: true,
    previewImage: '',
    templateType: 'general',
    config: {
      headingFont: 'Montserrat',
      bodyFont: 'Inter',
      baseFontSize: 16,
      navbarStyle: 'sticky',
      showNavCTA: true,
      navCTAText: 'Contact Agent',
      primaryColor: '#065f46',
      secondaryColor: '#059669',
      bgLight: '#FFFFFF',
      bgDark: '#0f172a',
      cardBg: '#f0fdf4',
      textColor: '#111827',
      sections: { hero: true, features: true, services: true, testimonials: true, gallery: true, faq: true, contactForm: true, footer: true },
      footerColumns: 4,
      footerCopyright: '© 2026 Real Estate. All rights reserved.',
      socialLinks: { facebook: '', instagram: '', twitter: '', youtube: '', linkedin: '' },
      logoUrl: '',
      faviconUrl: '',
      heroLayout: 'fullscreen',
      heroTitle: 'Find Your Dream Home',
      heroSubtitle: 'Discover the perfect property with expert guidance',
      heroBgImage: '',
      heroCTAText: 'Browse Properties',
    },
  },
]

async function addTemplates() {
  try {
    await mongoose.connect(MONGODB_URI)
    console.log('✅ Connected to MongoDB')

    // Clear existing templates (optional - comment out if you want to keep existing)
    // await Template.deleteMany({})
    // console.log('🗑️  Cleared existing templates')

    // Insert templates
    const result = await Template.insertMany(templates)
    console.log(`✅ Added ${result.length} templates successfully!`)

    console.log('\n📋 Templates added:')
    result.forEach((t, i) => {
      console.log(`${i + 1}. ${t.name} (${t.category}) - Homepage: ${t.showOnHomepage ? '✓' : '✗'}`)
    })

    await mongoose.connection.close()
    console.log('\n✅ Done! Database connection closed.')
  } catch (error) {
    console.error('❌ Error:', error)
    process.exit(1)
  }
}

addTemplates()
